<a href="https://colab.research.google.com/github/codypai123432/MyPractice_Code/blob/practice-changes-2026-05-27/introduction_to_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PYTHON INTRODUCTION

#                                                      Table Of Content
1.introdution

     1.1 What is Python
     
2.Data types

     2.1 variables
     2.2 Numbers
     2.3 Strings
     2.4 Lists
     2.5 Dictionaries
     2.6 Tuples
     2.7 Sets
   
3.Comparison operators

4.If-Else statement

5.For Loop and While loop

6.Functions

7.Lambda functions

     7.1 Map()
     7.2 Filter()
   
8.File I/O

9.Pandas liberary introduction

10.Series

     10.1 From ndarray
     10.2 From dict
     10.3 From scalar value
     10.4 Series is ndarray-like
     10.5 Series is dict-like
     10.6 Vectorized operations and label alignment with series
   
11.Data frames

     11.1 From dict of series or dicts
     11.2 from dict of ndarrays/lists
     11.3 from a list of dicts
     11.4 from a list of tuples
     11.5 Alternate constructors
     11.6 Column selection, addition, deletion
     11.7 Indexing/ selection
     11.8 Data alignment
     11.9 transposing

# 1. Introduction

## 1.1 What is python

Guido Van Rossum developed the Python language in the late 1980s. In contrast to other popular languages such as C, C++, Java, and C#, Python strives to provide a simple but powerful syntax.It is open source general purpose language with great interactive environment.It provides all the three types of programming features Object Oriented, Procedural and Functional.It is used by many of the most highly productive professional programmers.Moreover, Python can also become a common language for production of web based analytics product. A few of the places that use Python extensively are Google, the New York Stock Exchange, Industrial Light,Magic etc.
#### Important features of Python:
 -  Built-in high level data types: strings, lists, dictionaries, etc.
 -  The usual control structures: if, if-else, if-elif-else, while, plus a powerful collection iterator (for).
 -  Multiple levels of organizational structure: functions, classes, modules, and  packages. These assist in organizing code. An excellent and large example is the Python standard library.
 - Compile on the fly to byte code -- Source code is compiled to byte code without a separate compile step. Source code modules can also be "pre-compiled" to byte code files.
 - Object-oriented -- Python provides a consistent way to use objects: everything is an object. And, in Python it is easy to implement new object types (called classes in object-oriented programming).
 - Extensions in C and C++ -- Extension modules and extension types can be written by hand. There are also tools that help with this, for example, SWIG, sip, Pyrex

# 2. Data types

There are various data types in Python. Some of the important types are listed below.

## 2.1 Variables

 - Python variables do not need explicit declaration to reserve memory space.
 - The declaration happens automatically when you assign a value to a variable.
 - The equal sign = is used to assign values to variables.
  
  Some examples are given as follows:

In [ ]:
area = 200.30  #float type variable
Distance = 100 #integer type variabe
name = 'Sara' #string type variable
x = "Hello"
y = 10.05

#print all values
print(area)
print(Distance)
print(name)
print(x)
print(y)

# My Variable Example: Variable

temperature = 21.5   # float type variable
students = 18        # integer type variable
course = "Exploring AI"   # string type variable
city = "Lethbridge" # string type variable
year = 2026  # integer type variable

# Print all values

print(temperature)
print(students)
print(course)
print(city)
print(year)

200.3
100
Sara
Hello
10.05
21.5
18
Exploring AI
Lethbridge
2026

## 2.2 Numbers

 - This data type store numeric values
 - Numbers are immutable data types (Immutable data types means values cannot be changed after it is created)

  Some examples are given as follows:

In [ ]:
5 #integer

5

In [ ]:
10+10 #integer

20

In [ ]:
5.5+5.5 #float

11.0

In [ ]:
5**2 #exponent

25

## 2.3 Strings

 - Strings in Python are identified as a contiguous set of characters represented in the quotation marks.
 - Python allows either pair of single or double quotes.
 - Strings are immutable.
 - Python doesn't support Char data type.It will beas string of length one in python.

In [ ]:
Course="Artificial Intelligence"
name='Sara'
print(name, Course)

## My Strings Example

school= "University of Lethbridge"
major="New Media"

print(school,major)

Sara Artificial Intelligence
University of Lethbridge New Media

### Access values in strings

 - we can access a specific character or range of characters from strings.
 - Subsets of strings can be taken using the slice operator [] and [:] with indexes starting from 0.

 Some examples are listed below:

In [ ]:
stringVariable = 'Hello World'

print("stringVariable[0]:", stringVariable[0])
print("stringVariable[1:5]:", stringVariable[1:5])

## Example of acesssing value in stings

stringVariable = 'Harry Potter'

print("stringVariable[0]:",stringVariable[0])
print("stringVariable[1:8]:",stringVariable[1:3] )
print("stringVriable[1:8]", stringVariable[2:3])

stringVariable[0]: H
stringVariable[1:5]: ello
stringVariable[0]: H
stringVariable[1:8]: ar
stringVriable[1:8] r

### Updating string

 - Value of string can be changed or updated by assigning a new value to it.
 - New value must have same data type as previous value.
 - For this purpose '+' operator is used as follows:

In [23]:
stringVariable ="Hello World "
stringVariable = stringVariable[:6]+"Python"


print("updated string:",stringVariable)


# Example of my work

stringVariable02 = "Harry Potter"
stringVariable03 = stringVariable02[:6] + "Python"
stringVariable04 =stringVariable02[0:4] +"Pai"


print("updated string:", stringVariable03)
print("updated string:",stringVariable04)

updated string: Hello Python
updated string: Harry Python
updated string: HarrPai

### Delete string

 - we can delete the value of string by just deleteing its object.
 - 'del' keyword is used for this purpose

  It would be cleared by using following example:

In [ ]:
stringVariable ="Hello World "
print(stringVariable)
del stringVariable
print(stringVariable)

## Example of my work

stringVariable ="Harry Potter "
print(stringVariable)
del stringVariable
print(stringVariable)

Hello World

NameError: name 'stringVariable' is not defined

### String special operators

 - some special operators are used in Python to perform different opertions.
   These are given below:

#### String Concatenation

 - To concatenate the strings we used '+' operator.

    Following are the examples of concatenation:

In [ ]:
stringvalue1="machine"
stringvalue2="learning"
print(stringvalue1+stringvalue2)


# Example
stringvalue1 = "digital"
stringvalue2 = "archive"
print(stringvalue1 + stringvalue2)

machinelearning
digitalarchive

#### Repitition

 - '*' symbol is used for repitition.

In [ ]:
stringvalue="Assignment"
print(stringvalue*2)

# Example

stringvalue = "Research"
print(stringvalue * 2)

AssignmentAssignment
ResearchResearch

#### Use of [] symbol

 - '[]'symbol give the character of string at given index.

In [ ]:
Stringvalue="Machine Learning"
print(Stringvalue[1])

#Example

stringvalue = "Design"
print(stringvalue * 2)

a
DesignDesign

#### Use of [:] symbol

 - [:] is used to get substring from string.

In [ ]:
stringvalue="Hello"
print(stringvalue [1:3])

# Example
Stringvalue = "Digital Archive"
print(Stringvalue[1])

el
i

#### use of 'in'

 - 'in' is used to check the existance of character in string.
 - It returns TRUE if given character exist in string,otherwise FALSE.

In [ ]:
Stringvalue="Hello"
print('H' in Stringvalue)

#Example

Stringvalue= "Hibernation"
print("b" in Stringvalue)

True
True

#### Use of "not in"

 - 'not in' returns true if given character is not in string,otherwise false.

In [ ]:
Stringvalue="Hello"
print('G' not in Stringvalue)
#Example
Stringvalue= "Cody"
print('F' not in Stringvalue)

True
True

### String formatting operator

 - Python uses C-style string formatting to create new, formatted strings.
 - The "%" operator is used to format in print statement.

See following examples:

In [ ]:
print("My name is %s and weight is %d kg!" % ("Sara", 21))

# Example
print('My name is %s and weight is %d kg!'% ('Cody',25))

My name is Sara and weight is 21 kg!
My name is Cody and weight is 25 kg!

## 2.4 Lists

 - Multiple types of data can be stored in a list.
 - A list contains items separated by commas and enclosed within square brackets [].
 - Individual elements of a list can be changed
 - list indices start with 0 just like arrays.

In [ ]:
list1 = [ 'Mary', 2000 ]

print(list1) # Prints complete list

# Example
list2 = ['Carol', 3000]
print(list2) # printns complete list

['Mary', 2000]
['Carol', 3000]

### Accessing values in list

 - Square brackets are used to access the values of a list
 - We can access specific values or range of values from a list

In [ ]:
list1 = [ 'Physics' , 'Chemistry' , 1857, 3290]
list2 = [1,2,3,4,5,6,7]

print("list1[0]: ", list1[0])
print("list2[1:5]: ", list2[1:5])


#Example

list1 = ['Design', 'Archive', 2025, 2026]

list2 = [10, 20, 30, 40, 50, 60, 70]

print("list1[0]: ", list1[0])

print("list2[1:5]: ", list2[1:5])

list1[0]:  Physics
list2[1:5]:  [2, 3, 4, 5]
list1[0]:  Design
list2[1:5]:  [20, 30, 40, 50]

### Updating list

 - Value of string can be changed or updated by assigning a new value to it.
 - we can update single or multiple elements of a list by giving slice on left hand of the assignment operator.
 - we can also update list by using append() function.

In [32]:
list1=["dell","Hp","Apple"]
list1[1]="samsung"
print(list1)

list1.append('acer')
print(list1)

# Example

list3=["apple","banada","mango"]
list3[2]="apple"
print(list3)

list3.append('orange')
print(list3)

['dell', 'samsung', 'Apple']
['dell', 'samsung', 'Apple', 'acer']
['apple', 'banada', 'apple']
['apple', 'banada', 'apple', 'orange']

### Delete List Element

- we can delete the element of list by using del keyword or remove()function.
- 'del' keyword is used when you know the position or index of element to be deleted.
- remove() function can be used when you don't know the postion of element to be removed.

  It would be cleared by using following example:

In [ ]:
list1=["dell","Hp","Apple"]
print(list1) # Prints complete list
del list1[1]  # To print out the del list one no need to define a new value?
print("After deleting the value ")
print(list1)

# Example
list1 = ["Photoshop", "Illustrator", "Blender"]

print(list1)  # Prints complete list

list1.remove("Illustrator")

print("After deleting the value")

print(list1)

['dell', 'Hp', 'Apple']
After deleting the value
['dell', 'Apple']
['Photoshop', 'Illustrator', 'Blender']
After deleting the value
['Photoshop', 'Blender']

In [ ]:
list1=["dell","Hp","Apple"]
print(list1) # Prints complete list

list1.remove('Hp')
print("After deleting the value ")
print(list1)


#Example

list1 = ["Archive", "Museum", "Gallery"]

print(list1)  # Prints complete list

list1.remove("Museum")

print("After deleting the value")

print(list1)

['dell', 'Hp', 'Apple']
After deleting the value
['dell', 'Apple']
['Archive', 'Museum', 'Gallery']
After deleting the value
['Archive', 'Gallery']

## 2.5 Dictionaries

 - Dictionary is an unordered set of key: value pairs, with the requirement that the keys are unique (within one dictionary).
 - Each key is seperated by colon(:) from its value.
 - Each item is seperated with comma(,).
 - A pair of braces creates an empty dictionary: {}.
 - Python's dictionaries are kind of hash-table type.
 - A dictionary key can be almost any Python type, but are usually numbers or strings. Values, on the other hand, can be any       arbitrary Python object.
 - Dictionaries are enclosed by curly braces ({ }) and values can be assigned and accessed using square braces ([])
 - Dictionaries have no concept of order among elements. It is incorrect to say that the elements are "out of order"; they are simply unordered

## Accessing value in dictionary

- Square brackets [] along with the key are used to access its value.

In [ ]:
dict1 = {'Name':"Sara" , "Department" : "SIAT", "Batch":2023}
print(dict1['Name'])

#Example
dict1 = {'Name': "Cody", "Department": "New Media", "Year": 2026}

print(dict1['Name'])

Sara
Cody

### Updating Dictionary

- we can update values in dictionary
- we can also add new values in dictionary

Some examples are given below:

In [3]:
dict1 = {'Name':"Sara" , "Department" : "SIAT", "Batch":2023}
print(dict1)
dict1['Batch']="S23"
print(dict1)

# Example

dict2 = {'Name':'Cody', "Department":"'New Media","Batch":2026}
print(dict1)
dict1['Batch']="S26"
print(dict1)

{'Name': 'Sara', 'Department': 'SIAT', 'Batch': 2023}
{'Name': 'Sara', 'Department': 'SIAT', 'Batch': 'S23'}
{'Name': 'Sara', 'Department': 'SIAT', 'Batch': 'S23'}
{'Name': 'Sara', 'Department': 'SIAT', 'Batch': 'S26'}

### Delete Dictionary element

- we can delete elements of dictionary as well as complete content of dictionary.
- To delete single element del keyword is used.
- clear() function  is used to remove complete dictionary.

 Some examples are as follows:

In [5]:
dict1 = {'Name':"Sara" , "Department" : "SIAT", "Batch":2023}
print(dict1)

del dict1['Batch']
print(dict1)


#Example

dict2 = {'Name': "Cody", "Department" : "SIAT", "Batch":2026}

del dict2['Department']
print(dict2)

{'Name': 'Sara', 'Department': 'SIAT', 'Batch': 2023}
{'Name': 'Sara', 'Department': 'SIAT'}
{'Name': 'Cody', 'Batch': 2026}

In [12]:
dict1 = {'Name':"Sara" , "Department" : "SIAT", "Batch":2023}
dict1.clear()
print(dict1)

#Example

dict2 = {'Name':"Nathan","Department" : "Sociology","Batch":2025}
dict2.clear()
print(dict2)

{}
{}

## 2.6 Tuples

 - A tuple is another sequence data type that is similar to the list.
 - A tuple consists of a number of values separated by commas. Unlike lists, however, tuples are enclosed within parenthesis.
 - The main difference between lists and tuples are − Lists are enclosed in brackets ( [ ] ) and their elements and size can be  changed, while tuples are enclosed in parentheses ( ( ) ) and cannot be updated. Tuples can be thought of as read-only lists.   
 - It can also have multiple data type values.

  For example:

### Accessing values in Tuples

- Square brackets [] along with the index are used to access its value.

In [6]:
tuple1 = ( 'simon','sara' , '20', 'saira40')

print(tuple1)
print(tuple1[1:3])


# Example

tuple2 = ('Pai', 'Cody','25', '39678')

print(tuple2)
print(tuple2[1:5])

('simon', 'sara', '20', 'saira40')
('sara', '20')
('Pai', 'Cody', '25', '39678')
('Cody', '25', '39678')

### Updating Tuples

- Tuples are immutable means we cannot change the value of tuple.
- It is read only.
- we are able to take portions of tuples to make a new tuple.

In [13]:
tuple1=('sun','mon','tue','wed','thur','fri' , 'sat')
tuple2=(1,2,3,4,5,6,7)
print(tuple1)
print(tuple2)
tuple3=(tuple1+tuple2)
print(tuple3)

# Example

tuple1=('jan', 'feb','march','april','may','june')
tuple2=(2,3,4,5)
print(tuple1)
print(tuple2)
tuple3=(tuple1+tuple2)
print(tuple3)

('sun', 'mon', 'tue', 'wed', 'thur', 'fri', 'sat')
(1, 2, 3, 4, 5, 6, 7)
('sun', 'mon', 'tue', 'wed', 'thur', 'fri', 'sat', 1, 2, 3, 4, 5, 6, 7)
('jan', 'feb', 'march', 'april', 'may', 'june')
(2, 3, 4, 5)
('jan', 'feb', 'march', 'april', 'may', 'june', 2, 3, 4, 5)

### Delete tuple elements

- we cannot delete single elements of tuple because they cannot be updated.
- To delete entire elements del keyword is used.

 Some examples are as follows:

In [21]:
tuple1=('sun','mon','tue','wed','thur','fri' , 'sat')
tuple2=(1,2,3,4,5,6,7)
print(tuple1)
print(tuple2)
del(tuple1)
tuple3= (tuple1+tuple2)
print(tuple3)


# Example

tuple1=('jan', 'feb','march','april','may','june')
tuple2=(2,3,4,5)
print(tuple1)
print(tuple2)
del(tuple1)
tuple3=(tuple1+tuple2)
print(tuple3)

('sun', 'mon', 'tue', 'wed', 'thur', 'fri', 'sat')
(1, 2, 3, 4, 5, 6, 7)

NameError: name 'tuple1' is not defined

# 2.7 Sets

 - A set is an unordered collection in which each value occurs at most once.
 - You can use curly braces to give an expression whose value is a set.
 - Python prints sets using curly braces.
 - Every value in a set is immutable but the set itself is immutable we can add o remove items from it.
 - Sets can be used to perform mathematical operations like union,intersection,etc
 - Empty set will be written as {}.
 - We can also make a set from a list using set() function.
 - Data type can be found using type() function.
 - add() is used to add single value, update() is used for adding multiple values.
 - update() function can take tuple,string,list or other set as argument.
 - discard() and remove() are used to delete specific item from list.
 - discard() will not raise an error if item doesn't exist.
 - remove() will raise an error if item doesn't exist in set.
 - The cardinality of a set S is the number of elements in the set.
 - In Python, the cardinality of a set is obtained using the function len(·).

In [1]:
#list
list1=[1,2,3,4,5]

print(type(list1))

my_set=set(list1)

print(type(my_set))

#set of integers
my_set={1,2,3}
print(my_set)

#set of mixed data types
my_set={1, "Hello"}

#adding a single value
my_set.add("D")

#adding multiple values
my_set.update(list1)
print(my_set)


my_set.discard('G') #it will not raise an error
my_set.remove('G') #it will raise an error



# Example

list1 =[10,20.30,40]

print(type(list1)) # Show that list1 is a list

my_set = set(list1) # Converts the list into a set

print(type(my_set)) # Shows that my_set is a set

# set of integres
my_set ={2024,2025,2026}

print(my_set) # prints the set

#set of mixed data type

my_set = {1,"Archive"}

# Adding a single value

#Adding a single value
my_set.add('Design') #Adds one new value to the set

#Adding multiple values

my_set.update(list1) #Adds all values from list1 into the set

print(my_set)

my_set. discard('Research') #Does not cuse issue when value is not missing

my_set. remove('Research') #Cuase issue when value is missing

<class 'list'>
<class 'set'>
{1, 2, 3}
{1, 2, 3, 4, 5, 'D', 'Hello'}

KeyError: 'G'

# 3.Comparison Operators

 - Comparison operators are used to compare values and return TRUE/FALSE according to the situation.
 - Python defines the following comparison operators:

### Less than operator  (<)

In [41]:
10<17


9<12

True

### Less than equal to operator (<=)

In [42]:
15<=10

12<=15

True

### Equal to operatoe (==)

In [43]:
16==16

14==14

True

In [44]:
"Sara"=="sara"

"Cody" =="Cody"

True

In [ ]:
"ALI"=="ALI"

True

### Not equal to operator (!=)

In [45]:
3!=5

2!=6

True

### OR Operator

In [46]:
(10==10)or(10<17)

(9==9)or(9<7)

True

### And operator

In [47]:
(10==10)and (10<17)

(5==5)and(3<15)

True

# 4.If else statement

 - The if–else is used to make choices in Python code.
 - This is a compound statement.
 - The syntax is:
 - if c o n d i t i o n
          action −1
  else :
          action −2
 - The indentation is required

In [48]:
x = 3
if x > 0:
    print(" sunday is wonderful")
else :
    print(" Monday is Good ")

# Example

x =4

if x>0:
  print ("That make sense")
else :
  print ("Try again!")

 sunday is wonderful
That make sense

In [50]:
if 25 % 2:
  print("Even")
else:
  print("Odd")


# Example

if 80 % 2:
  print("Even")
else:
  print("Odd")

Even
Odd

# 5.For and while loop

- Python has for and while loop for iteration,used when we want to perfrom a specific task repeatedly.

### For loop

- The for statement is used to iterate over the elements of a sequence.
- It's traditionally used when you have a piece of code which you want to repeat n number of time.
- The syntax of a for loop is:

    for item in list :
      a c t i o n
- As usual, the action consists of one or more statements, all at the same indentation level. These statements are also known as the body of the loop. The item is a variable name, and list is a list.
- Execution of the for loop works by setting the variable successively to each item in the list, and then executing the body each time.

  Here is a simple example:

In [84]:
for i in [2 , 4 , 6 , 0]:
    print(i)

# Example

for i in [20,40,60,70]:
  print(i)
  print((i+1)%3)

2
4
6
0
20
0
40
2
60
1
70
2

In [52]:
for counter in range(1, 6):
    print(counter)

# Example

for fruit in range (1,10):
  print(fruit)

1
2
3
4
5
1
2
3
4
5
6
7
8
9

In [53]:
word = "sara"
for letter in word:
    print(letter)

# Example

name = 'Cody'

for letter in name:
  print(name)

s
a
r
a
Cody
Cody
Cody
Cody

### While loop

In [60]:
a=0
while a < 10:
  a=a+1
  print(a)

#Example

b=2
while b < 20:
  b=b+1
  print(b)

1
2
3
4
5
6
7
8
9
10
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20

# 6.Functions

 - You use functions in programming to bundle a set of instructions that you want to use repeatedly or that, because of their  complexity, are better self-contained in a sub-program and called when needed.                                 
 - Function is a piece of code written to carry out a specified task.
 - There are three types of functions in Python:
 - Built-in functions, such as help() to ask for help, min() to get the minimum value, print() to print an object.
 - User-Defined Functions (UDFs), which are functions that users create to help them out.
 - Anonymous functions, which are also called lambda functions because they are not declared with the standard def keyword.
 - The syntax is:

   def functionname(parameters)
    
   "function_docstring"
   
   function_suite
   
   return [expression]

In [61]:
def my_function(name):
  #This prints a passed string into this function
    print(name)
    return;

#Now you can call my_function
my_function("Mary")


# Example

def my_function(title):
  #This prints a passed string into this function
    print(title)
    return;

#Now you can call my_function
my_function("Cody")

Mary
Cody

# 7.Lambda Functions

 - The creation of anonymous functions at runtime,using a construct called "lambda"
 - A lambda function is a small anonymous function.
 - A lambda function can take any number of arguments, but can only have one expression.
 - Lambda function does not include return statement,it always contains an expression which is returned.
 - You might want to use lambdas when you don’t want to use a function twice in a program.

   some examples are given:

In [75]:
#Normal Function
def f (x):
  return x**2
print(f(8))

#Abnormal Function
def f(y,x,z):
  return y*2*x*z-z
print (f(10,3,2))

64
118

In [64]:
times3 = lambda var:var*3
times3(10)

# Example

times4 = lambda var:var*4
times4(10)

#lamba expressions : another way to write a function in line

40

In [67]:
add = lambda x, y: x + y

print(add(3, 5))

# Example

Multiply= lambda x, y: x*y

print(Multiply(10, 20))

8
200

## 7.1 Map()

 - Map() function is used with two arguments.Just like: r=map(func,seq)
 - The first argument func is function name and the second is a sequence(list etc)
 - Map functions expects a function object and any number of iterables like list, dictionary, etc.
 - It executes the function_object for each element in the sequence and returns a list of the elements modified by the function  object.

   Example:

In [85]:
sentence = "It is raining cats and dogs"
words = sentence.split()
print(words)

lengths= map(lambda word :len(word), words)

list(lengths)

# Example

sentence = "Digital archives preserve cultural memory"
words = sentence.split()  # Splits the sentence into separate words
print(words)  # Prints the list of words
lengths = map(lambda word: len(word), words)  # Counts the letters in each word
print(list(lengths))  # Converts the results into a list and prints them

['It', 'is', 'raining', 'cats', 'and', 'dogs']
['Digital', 'archives', 'preserve', 'cultural', 'memory']
[7, 8, 8, 8, 6]

## 7.2 Filter()

 - The filter() method filters the given iterable with the help of a function that tests each element in the iterable to be true or not.
 - The syntax of filter() method is:
      filter(function, iterable)
 - The filter() method takes two parameters:

      1)function - function that tests if elements of an iterable returns true or false If None, the function defaults to Identity function - which returns false if any elements are false
      
      2)iterable - iterable which is to be filtered, could be sets, lists, tuples, or containers of any iterators
 - The filter() method returns an iterator that passed the function check for each element in the iterable.

In [86]:
# list of alphabets
alphabets = ['a', 'b', 'd', 'e', 'i', 'j', 'o']

# function that filters vowels
def filterVowels(alphabet):
    vowels = ['a', 'e', 'i', 'o', 'u']

    if(alphabet in vowels):
        return True
    else:
        return False

for i in filter(filterVowels, alphabets):
     print(i)


# List of project types
projects = ['Design', 'Archive', 'Research', 'Video', 'Painting']

# Function that filters selected project types
def filterProjects(project):
    selected = ['Archive', 'Research', 'Video']

    if project in selected:
        return True
    else:
        return False

# Prints only the project types that match the filter
for i in filter(filterProjects, projects):
    print(i)

a
e
i
o
Archive
Research
Video

In [ ]:
# random list
randomList = [1, 'a', 0, False, True, '0']

filteredList = filter(None, randomList)

print('The filtered elements are:')
for element in filteredList:
    print(element)

In [ ]:
ages = [5, 12, 17, 18, 24, 32]

def myFunc(x):
  if x < 18:
    return False
  else:
    return True

adults = filter(myFunc, ages)

for x in adults:
  print(x)

# 8.File I/O

 - In this section we will cover basic I/O functions.

## Reading input from keyboard

 -  There are two functions in Python that you can use to read data from the user:raw_input and input
 -  You can store the results from them into a variable
 -  If the input function is called, the program flow will be stopped until the user has given an input and has ended the input  with the return key. The text of the optional parameter, i.e. the prompt, will be printed on the screen.

 Let's have a look at the following example:

In [ ]:
name = raw_input("What's your name? ")
print("Nice to meet you " + name + "!")

In [88]:
age = raw_input("What's your age? ")
print("your age is " + age + "!")

NameError: name 'raw_input' is not defined

In [87]:
string=raw_input("enter your university....")
print(string)

NameError: name 'raw_input' is not defined

## I/O From or to text file

 - In this scenario, we will read and write to a text file.
 - we can open files in different modes.

## Read only mode

 - r opens a file in read only mode.
 - The file pointer is placed at the beginning of the file.
 - This is the default mode.

In [ ]:

file = open("hello.txt", "r")
str=file.read();
print(str)
file.close()

# Example
file = open("research.txt", "r")  # Opens the file in read mode

text = file.read()  # Reads all the content from the file

print(text)  # Prints the file content

file.close()  # Closes the file

## Read and write mode

 - r+ opens a file in read and write mode.
 - The file pointer placed at the beginning of the file

In [89]:
# Open a file
file = open("hello.txt", "r+")
str = file.read(10);
print "Read String is : ", str
# Close opend

# Example

# Open a file in read and write mode
file = open("hello.txt", "r+")

text = file.read(10)  # Reads the first 10 characters from the file

print("Read String is:", text)  # Prints the characters that were read

file.close()  # Closes the file

SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)? (1245104769.py, line 4)

## Write mode only

 - w opens a file in write mode only.
 - Overwrites the file if the file exists. If the file does not exist, creates a new file for writing

In [ ]:
file = open('write.txt','w')
file.write("This is the write command")
file.write("It allows us to write in a particular file")
file = open('write.txt','r')
str=file.read()
print(str)
file.close()

## Append mode

 - a opens a file in append mode.
 - The file pointer is at the end of the file if the file exists.
 - That is, the file is in the append mode. If the file does not exist, it creates a new file for writing.

In [ ]:
file = open('write.txt','a')
file.write("This will add this line")
file = open('write.txt','r')
str=file.read()
print(str)
file.close()

## Append and read mode

 - a+ opens a file in append and read mode.
 - The file pointer is at the end of the file if the file exists. The file opens in the append mode. If the file does not exist,    it creates a  new file for reading and writing.

In [ ]:
file = open('hello.txt','a+')
file.write("MSCS From comsats university")
file.close()
file = open('hello.txt','r')
str=file.read()
print(str)
file.close()

## File Position

 - tells() method tells the current position within the file.
 - seek() method changes the current file method.
 - Following is the syntax for seek() method:    fileObject.seek(offset[, whence])

In [ ]:
f = open('hello.txt',"r+")
str=f.read(20);
print("read string is :",str)

position=f.tell();
print("current file position is :",position)

position=f.seek(5);
str=f.read(10);
print("again read string is :",str)
f.close()

# 9.Pandas Introduction

Pandas is an open-source Python Library providing high-performance data manipulation and analysis tool using its powerful data structures. The name Pandas is derived from the word Panel Data – an Econometrics from Multidimensional data. In 2008, developer Wes McKinney started developing pandas when in need of high performance, flexible tool for analysis of data.

Prior to Pandas, Python was majorly used for data munging and preparation. It had very less contribution towards data analysis. Pandas solved this problem. Using Pandas, we can accomplish five typical steps in the processing and analysis of data, regardless of the origin of data — load, prepare, manipulate, model, and analyze.

Python with Pandas is used in a wide range of fields including academic and commercial domains including finance, economics, Statistics, analytics, etc.

#### Key Features of Pandas

-  Fast and efficient DataFrame object with default and customized indexing.
-  Tools for loading data into in-memory data objects from different file formats.
-  Data alignment and integrated handling of missing data.
-  Reshaping and pivoting of date sets.
- Label-based slicing, indexing and subsetting of large data sets.
- Columns from a data structure can be deleted or inserted.
- Group by data for aggregation and transformations.
- High performance merging and joining of data.
- Time Series functionality.

Pandas deals with the following three data structures:
- Series
- DataFrame
- Panel

These data structures are built on top of Numpy array, which means they are fast.

# 10.Series

- The Series is a one-dimensional array that can store various data types, including mix data types.
- The row labels in a Series are called the index.
- Any list, tuple and dictionary can be converted in to Series using ‘series’ method
- Basic method to create a series: s = pd.Series(data, index = index)
- Series is size immutable.

In [94]:
import pandas as pd
s = pd.Series([1, 'Lahore', 2, 3, 'Happy Eating!'])
print(s)

#Example

import pandas as pd  # Imports the pandas library
s = pd.Series([2026, 'Digital Archive', 5, 10, 'Research Project'])
print(s)  # Prints the pandas Series

0                1
1           Lahore
2                2
3                3
4    Happy Eating!
dtype: object
0                2026
1     Digital Archive
2                   5
3                  10
4    Research Project
dtype: object

## 10.1 Series creation from ndarray

- Index must be of same length as data. If no index is passed, it will automatically be [0, ..., len(data) - 1]

In [99]:
first_series = pd.Series([1,2,4,8,16,32,64])
print(type(first_series))
print(first_series)

# Example

import pandas as pd  # Imports the pandas library

second_series = pd.Series([10, 20, 30, 40, 50])

print(type(second_series))  # Shows the data type of first_series

print(second_series)  # Prints the complete Series

<class 'pandas.core.series.Series'>
0     1
1     2
2     4
3     8
4    16
5    32
6    64
dtype: int64
<class 'pandas.core.series.Series'>
0    10
1    20
2    30
3    40
4    50
dtype: int64

In [107]:
import numpy as np
s = pd.Series(np.random.randn(5), index=['a', 'b', 'c', 'd', 'e'])
print(s)
print('-'*50)
print(s.index)


# Example

import numpy as np

y = pd.Series(np.random.randn(6), index=['z', 'b', 'g', 'e', 'a','e'])

print(y)
print('-'*50)
print(y.index)

a    0.783245
b   -1.733795
c   -0.918261
d    2.017374
e    0.394103
dtype: float64
--------------------------------------------------
Index(['a', 'b', 'c', 'd', 'e'], dtype='object')
z    0.318974
b   -0.148155
g    0.233609
e   -0.530765
a    1.243945
e    0.169144
dtype: float64
--------------------------------------------------
Index(['z', 'b', 'g', 'e', 'a', 'e'], dtype='object')

## 10.2 Series creation from dict

- If Data is a dictionary, if index is passed the values in data corresponding to the labels in the index will be pulled out, otherwise an index will be constructed from the sorted keys of the dict.

In [ ]:
d = {'a': 100., 'b': 200., 'c': 300.}
pd.Series(d)

a    100.0
b    200.0
c    300.0
dtype: float64

In [ ]:
data = {'abc': 1, 'def': 2, 'xyz': 3}
pd.Series(data)

abc    1
def    2
xyz    3
dtype: int64

## 10.3 Series creation from a scalar value

- Index must be provided. The value will be repeated to match the length of the index

In [102]:
pd.Series(5, index = ['a', 'b', 'c'])

# Example

pd.Series(6,index=['b','c','d','e'])

b    6
c    6
d    6
e    6
dtype: int64

In [104]:
 x = pd.Series(3, index=['a', 'b', 'c', 'd'])
x

# Example

y= pd.Series(10,index=['a','b','c','d,e,g'])
y

a        10
b        10
c        10
d,e,g    10
dtype: int64

## 10.4 Series is ndarray-like

- Series acts similar to a numpy array, and is valid arguments to most numpy functions.
- Slicing also slices the index
- Short Intro, back to this later

In [108]:
import pandas as pd  # Imports pandas
import numpy as np  # Imports NumPy

s = pd.Series(
    np.random.randn(5),
    index=['AI', 'Design', 'Archive', 'Media', 'Research']
)  # Creates 5 random numbers with custom labels

print(s)  # Prints the Series

AI          0.743500
Design      2.090970
Archive    -1.610055
Media      -0.292155
Research    0.178550
dtype: float64

In [ ]:
s = pd.Series(np.random.randn(5), index=['a', 'b', 'c', 'd', 'e'])
print(s.iloc([2,1,4]))

TypeError: unhashable type: 'list'

In [109]:
s = pd.Series(np.random.randn(5), index=['a', 'b', 'c', 'd', 'e'])
print(s[:3])


# Example

import pandas as pd  # Imports pandas
import numpy as np  # Imports NumPy

s = pd.Series(
    np.random.randn(5),
    index=['AI', 'Design', 'Archive', 'Media', 'Research']
)  # Creates 5 random values with labels

print(s[:3])  # Prints the first 3 items in the Series

a    0.716199
b    0.317372
c    0.429407
dtype: float64
AI        -0.676192
Design    -2.191798
Archive   -0.276982
dtype: float64

In [110]:
s = pd.Series(np.random.randn(5), index=['a', 'b', 'c', 'd', 'e'])
print(s[[3,2,1]])

# Example

import pandas as pd  # Imports pandas
import numpy as np  # Imports NumPy

s = pd.Series(
    np.random.randn(5),
    index=['AI', 'Design', 'Archive', 'Media', 'Research']
)  # Creates 5 random values with labels

print(s[[3, 2, 1]])  # Prints items at positions 3, 2, and 1

d   -0.177807
c    1.398233
b   -0.107342
dtype: float64
Media     -0.844768
Archive   -0.002614
Design     0.415832
dtype: float64

/tmp/ipykernel_8663/3348428095.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(s[[3,2,1]])
/tmp/ipykernel_8663/3348428095.py:14: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(s[[3, 2, 1]])  # Prints items at positions 3, 2, and 1

In [111]:
s = pd.Series(np.random.randn(5), index=['a', 'b', 'c', 'd', 'e'])
np.exp(s)

# Example

import pandas as pd  # Imports pandas
import numpy as np  # Imports NumPy

s = pd.Series(
    np.random.randn(5),
    index=['AI', 'Design', 'Archive', 'Media', 'Research']
)  # Creates 5 random values with labels

print(np.exp(s))  # Calculates e raised to the power of each value

AI          1.975777
Design      0.549533
Archive     0.771938
Media       0.156094
Research    0.817103
dtype: float64

In [112]:
s = pd.Series(np.random.randn(5), index=['a', 'b', 'c', 'd', 'e'])
s['b']


# Example
import pandas as pd  # Imports pandas
import numpy as np  # Imports NumPy

s = pd.Series(
    np.random.randn(5),
    index=['AI', 'Design', 'Archive', 'Media', 'Research']
)  # Creates 5 random values with custom labels

print(s['Design'])  # Prints the value connected to the label "Design"

-1.110604819884096

In [114]:
s = pd.Series(np.random.randn(5), index=['a', 'b', 'c', 'd', 'e'])
s['b']=12.
s

# Example

import pandas as pd  # Imports pandas
import numpy as np  # Imports NumPy

s = pd.Series(
    np.random.randn(5),
    index=['AI', 'Design', 'Archive', 'Media', 'Research']
)  # Creates 5 random values with custom labels

print(s['Design'])  # Prints the value connected to the label "Design"

-0.70870387887735

In [116]:
s = pd.Series(np.random.randn(5), index=['a', 'b', 'c', 'd', 'e'])
'e' in s


# Example

import pandas as pd  # Imports pandas
import numpy as np  # Imports NumPy

s = pd.Series(
    np.random.randn(5),
    index=['AI', 'Design', 'Archive', 'Media', 'Research']
)  # Creates 5 random values with custom labels

print('Research' in s)  # Checks whether "Research" exists as an index label

True

In [117]:
s = pd.Series(np.random.randn(5), index=['a', 'b', 'c', 'd', 'e'])
'f' in s


# Example

import pandas as pd  # Imports pandas
import numpy as np  # Imports NumPy

s = pd.Series(
    np.random.randn(5),
    index=['AI', 'Design', 'Archive', 'Media', 'Research']
)  # Creates 5 random values with custom labels

print('Museum' in s)  # Checks whether "Museum" exists as an index label

False

## 10.5 Series is dict-like

- A Series is like a xed-size dict in that you can get and set values by index label

In [122]:
s = pd.Series([1, 2, 3, 4])
s.to_dict()

import pandas as pd  # Imports pandas
import numpy as np  # Imports NumPy

s = pd.Series(
    np.random.randn(5),
    index=['AI', 'Design', 'Archive', 'Media', 'Research']
)  # Creates 5 random values with custom labels

print('Museum' in s)  # Checks whether "Museum" exists as an index label

False

## 10.6 Vectorized operations and label alignment with Series

- When doing data analysis,as with the row NumPy arrays looping through series value by value is usually not necessary.
- Series can also be passed into most NumPy method expecting an ndarray.
- NumPy and Pandas generalize arithmetic operations so that we can easily and quickly perform the same operation on many array elements. For example:

In [120]:
import numpy as np
x = np.array([2, 3, 5, 7, 11, 13])
x * 2

#Example

import numpy as np  # Imports NumPy

x = np.array([10, 20, 30, 40, 50])  # Creates a NumPy array

print(x * 2)  # Multiplies every value in the array by 2

[ 20  40  60  80 100]

In [124]:
data = ['saima', 'aisha', 'faiza', 'saira']
[s.capitalize() for s in data]


# Example
data = ['archive', 'design', 'research', 'media']  # Creates a list of words

print([word.capitalize() for word in data]) # Capitalizes the first letter of each word

['Archive', 'Design', 'Research', 'Media']

# 11.Data Frames

- A DataFrame is a two dimensional object that can have columns with potential different types. Different kind of inputs include dictionaries, lists, series, and even another DataFrame.
- It is the most commonly used pandas object.
- You can create a series from:
    - Dict of 1D ndarrays, lists, dicts, or Series
    - 2-D numpy array
    - A list of dictionaries
    - A Series
    - Another Dataframe
  
- index/ columns is a list of the row/ column labels. If you pass an index and/ or columns, you are guarenteeing the index and /or column of the df.
- If you do not pass anything in, the input will be constructed by "common sense" rules

In [ ]:
dates = pd.date_range('20130101',periods=6)
dates

## 11.1 Dataframe creation from dict of series or dicts

 - The index of the resulting DataFrame will be the union of the indices of the various Series. If there are any nested dicts, these will be converted to Series.
 - If no columns are passed, the columns will be the sorted list of dict keys.

In [131]:
# Create a dictionary of series
d = {'one': pd.Series([1,2,3], index = ['a', 'b', 'c']),
'two': pd.Series(list(range(4)), index = ['a','b', 'c', 'd'])}
# Columns are dictionary keys, indices and values obtained from series
df = pd.DataFrame(d)
# Notice how it fills the column one with NaN for d
print(df)


# Example

d= {'Design':pd.Series([20,30,40], index=['a','b','c']),
    'Archive': pd.Series(np.random.randn(5), index=['a', 'b', 'c', 'd','e'])
    }

    # creates a dataframe from dictinonary
df=pd.DataFrame(d)
print(df)

   one  two
a  1.0    0
b  2.0    1
c  3.0    2
d  NaN    3
   Design   Archive
a    20.0 -0.490008
b    30.0  1.265967
c    40.0  0.692227
d     NaN  2.425602
e     NaN  0.310837

In [133]:
 d = {'col1': [1, 2], 'col2': [3, 4]}
 df = pd.DataFrame(data=d)
 df

 #Example

d = {
    'Archive': [10, 20],
    'Design': [30, 40]
}  # Creates a dictionary with two columns

df = pd.DataFrame(data=d)  # Converts the dictionary into a DataFrame

print(df)  # Prints the DataFrame

   Archive  Design
0       10      30
1       20      40

## 11.2  Dataframe creation from dict of ndarrays/lists

 - The ndarrays must all be the same length.
 - If an index is passed, it must clearly also be the same length as the arrays. If no index is passed, the result will be range(n), where n is the array length.

In [134]:
d = {'one' : [1., 2., 3., 4.], 'two' : [4., 3., 2., 1.]}
pd.DataFrame(d)

# Example

d = {
    'Archive': [1.0, 2.0, 3.0, 4.0],
    'Design': [4.0, 3.0, 2.0, 1.0]
}  # Creates a dictionary with two columns

df = pd.DataFrame(d)  # Converts the dictionary into a DataFrame

print(df)  # Prints the DataFrame

   Archive  Design
0      1.0     4.0
1      2.0     3.0
2      3.0     2.0
3      4.0     1.0

In [137]:
df2 = pd.DataFrame(np.random.randint(low=0, high=10, size=(5, 5)), columns=['a', 'b', 'c', 'd', 'e'])
df2

# Example

df2 = pd.DataFrame(
    np.random.randint(low=1, high=400, size=(4, 3)),
    columns=['Archive', 'Design', 'Research']
)  # Creates a 4-row, 3-column DataFrame with random integers

print(df2)  # Prints the DataFrame

   Archive  Design  Research
0       54     298       291
1      351     319        22
2       52     151       237
3      297     256       386

## 11.3 Dataframe creation from a list of dicts

In [138]:
data = [{'a':10,"b":20},{'a':5,'b':10,'c':20}]
pd.DataFrame(data)

# Example

data = [
    {'Archive': 10, 'Design': 20},
    {'Archive': 5, 'Design': 10, 'Research': 20}
]  # Creates a list containing two dictionaries

df = pd.DataFrame(data)  # Converts the list of dictionaries into a DataFrame

print(df)  # Prints the DataFrame

   Archive  Design  Research
0       10      20       NaN
1        5      10      20.0

In [139]:
data = [{'a':10,"b":20,"c":30},{'a':5,'b':10,'c':20}]
pd.DataFrame(data)


# Example

data = [
    {'Archive': 10, 'Design': 20, 'Research': 30},
    {'Archive': 5, 'Design': 10, 'Research': 20}
]  # Creates two rows of data

df = pd.DataFrame(data)  # Converts the list of dictionaries into a DataFrame

print(df)  # Prints the DataFrame

   Archive  Design  Research
0       10      20        30
1        5      10        20

## 11.4 Dataframe creation from a dict of tuples

 - You can automatically create a multi indexed by passing a tuple dictionary.

In [140]:

df = pd.DataFrame({'Initial': ['C','A','M'], 'Sex': ['M', 'F', 'F'], 'Age': [49, 39, 19]})
#df = df[['Initial', 'Sex', 'Age']]
df

# Example

df = pd.DataFrame({
    'Project': ['Archive', 'Design', 'Research'],
    'Type': ['Digital', 'Visual', 'Academic'],
    'Year': [2024, 2025, 2026]
})  # Creates a DataFrame with three columns

# df = df[['Project', 'Type', 'Year']]  # Reorders or selects these columns

print(df)  # Prints the DataFrame

    Project      Type  Year
0   Archive   Digital  2024
1    Design    Visual  2025
2  Research  Academic  2026

In [141]:
data = [('p1', 't1', 1, 2),('p1', 't2', 3, 4),('p2', 't1', 5, 6),('p2', 't2', 7, 8),('p2', 't3', 2, 8)]

df = pd.DataFrame(data)
df

# Example
data = [
    ('Archive', 'Image', 10, 20),
    ('Archive', 'Video', 30, 40),
    ('Design', 'Image', 50, 60),
    ('Design', 'Video', 70, 80),
    ('Research', 'Text', 20, 80)
]  # Creates a list of tuples

df = pd.DataFrame(data)  # Converts the tuples into a DataFrame

print(df)  # Prints the DataFrame

          0      1   2   3
0   Archive  Image  10  20
1   Archive  Video  30  40
2    Design  Image  50  60
3    Design  Video  70  80
4  Research   Text  20  80

## 11.5 Alternate constructors

### Dataframe.from_dict

 - Dataframe.from_dict takes a dict of dictsor a dict of array like sequences and returns a Dataframe.
 - It operates like the dataframe constructor except for the orient parameter which is coulmn by default,but which can be set to index in order to use the dict keys as row labels.

In [142]:
data = {"X": {'a': 1, 'b': 2, 'c': 3}, "Y": {'d': 4, 'e': 5, 'f': 6}, "Z": {'g': 7, 'h': 8, 'i': 9}}

df = pd.DataFrame.from_dict(data, orient="index").fillna(0).astype(int)
df


# Example

data = {
    "Archive": {'Image': 10, 'Video': 20, 'Text': 30},
    "Design": {'Image': 40, 'Audio': 50, 'Web': 60},
    "Research": {'Survey': 70, 'EEG': 80, 'AI': 90}
}  # Creates a nested dictionary

df = pd.DataFrame.from_dict(
    data,
    orient="index"
).fillna(0).astype(int)  # Rows come from outer keys, missing values become 0

print(df)  # Prints the DataFrame

          Image  Video  Text  Audio  Web  Survey  EEG  AI
Archive      10     20    30      0    0       0    0   0
Design       40      0     0     50   60       0    0   0
Research      0      0     0      0    0      70   80  90

### Dataframe.from_records

- Dataframe.from_records take a list of tuples or an ndarray with structured dtype.
- Works analogously to the normal dataframe constructor,except that index may be aspecific field of the structured dtype to use as the index.for example:

In [ ]:
sales = [('Jones LLC', 150, 200, 50),
     ('Alpha Co', 200, 210, 90),
     ('Blue Inc', 140, 215, 95)]
labels = ['account', 'Jan', 'Feb', 'Mar']
df = pd.DataFrame.from_records(sales, columns=labels)
df

     account  Jan  Feb  Mar
0  Jones LLC  150  200   50
1   Alpha Co  200  210   90
2   Blue Inc  140  215   95

### Dataframe.from_items

- Convert (key, value) pairs to DataFrame. The keys will be the axis index (usually the columns, but depends on the specified orientation). The values should be arrays or Series.

In [ ]:
df=pd.DataFrame.from_items([('A',[1,2,3]),('B',[4,5,6])]

SyntaxError: invalid syntax (<ipython-input-30-4c478132b779>, line 2)

In [ ]:
df=pd.DataFrame.from_items([('A',[1,2,3]),('B',[4,5,6])])
df

D:\python\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: from_items is deprecated. Please use DataFrame.from_dict(dict(items), ...) instead. DataFrame.from_dict(OrderedDict(items)) may be used to preserve the key order.
  """Entry point for launching an IPython kernel.

   A  B
0  1  4
1  2  5
2  3  6

## 11.6 Column selection,addition,deletion

 - You can treat a DataFrame semantically like a dict of like-indexed Series objects. Getting, setting, and deleting columns works with the same syntax as the analogous dict operations:

In [ ]:
df = pd.DataFrame([[1,2],[3,4],[5,6]], columns=['a','a']) # you can adress column by index
df

   a  a
0  1  2
1  3  4
2  5  6

In [ ]:
df = pd.DataFrame([[1,2],[3,4],[5,6]], columns=['a','a'])
df.columns = ['a','b']  # rename column
df

   a  b
0  1  2
1  3  4
2  5  6

In [ ]:
df = pd.DataFrame([[1,2],[3,4],[5,6]], columns=['a','b'])
del df['b']   # delete column
df

   a
0  1
1  3
2  5

In [ ]:
df = pd.DataFrame([[1,2],[3,4],[5,6]], columns=['a','b'])
df['c']='2'   #add new column c and fill with 2
df

   a  b  c
0  1  2  2
1  3  4  2
2  5  6  2

### 11.7 Indexing / seletion

- Row selection, for example, returns a Series whose index is the columns of the DataFrame:
- Pandas now supports three types of Multi-axes indexing; the three types are:
    - .loc()  (label based)
    - .iloc()  (integer based)
    - .ix()    (both label and integer based)
- loc takes two single/list/range operator separated by ','. The first one indicates the row and the second one indicates columns.
- iloc(): Pandas provide various methods in order to get purely integer based indexing. Like python and numpy, these are 0-based indexing.
- ix(): Besides pure label based and integer based, Pandas provides a hybrid method for selections and subsetting the object using the .ix() operator.

#### .loc()

In [ ]:
df = pd.DataFrame(np.random.randn(8, 4),
index = ['a','b','c','d','e','f','g','h'], columns = ['A', 'B', 'C', 'D'])

#select all rows for a specific column
print(df.loc[:,'A'])

a   -0.079142
b   -1.058681
c   -0.288618
d    1.305291
e   -0.142134
f   -1.700362
g    1.181158
h    1.580676
Name: A, dtype: float64

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.DataFrame(np.random.randn(8, 4),
index = ['a','b','c','d','e','f','g','h'], columns = ['A', 'B', 'C', 'D'])

# Select all rows for multiple columns, say list[]
print(df.loc[:,['A','C']])

In [ ]:
df = pd.DataFrame(np.random.randn(8, 4),
index = ['a','b','c','d','e','f','g','h'], columns = ['A', 'B', 'C', 'D'])

# Select range of rows for all columns
print(df.loc['a':'h'])

          A         B         C         D
a  0.037907  1.015942 -0.267717  1.894588
b  0.935796 -0.160951 -0.323399 -1.175658
c -0.169679  1.233065 -2.498030 -0.035843
d -0.347513 -1.111108  0.259755 -0.382133
e  0.355051 -0.882159 -0.289581 -0.357559
f -2.254955 -2.390495  0.307529  1.269759
g  0.220503 -0.769530 -0.207382  0.005101
h -1.264961  0.385471 -1.854020  0.627250

#### .iloc()

In [ ]:
df = pd.DataFrame(np.random.randn(8, 4), columns = ['A', 'B', 'C', 'D'])

# select all rows for a specific column
print(df.iloc[:4])

          A         B         C         D
0  0.885934  0.448261  0.584728  0.074509
1  0.670950  1.247670 -1.150118  0.769580
2  0.220727 -0.372701  0.232594  0.188892
3 -0.141555  0.356357  0.119643  0.125009

In [ ]:
df = pd.DataFrame(np.random.randn(8, 4), columns = ['A', 'B', 'C', 'D'])

# Integer slicing

print(df.iloc[1:5, 2:4])

          C         D
1 -0.600980  2.148089
2  0.622637  0.357187
3 -0.038853 -0.265465
4  0.049228 -0.269615

#### .ix()

In [ ]:
df = pd.DataFrame(np.random.randn(8, 4), columns = ['A', 'B', 'C', 'D'])

# Integer slicing
print(df.ix[:4])

          A         B         C         D
0 -1.518915 -0.496256 -1.905349  0.325399
1 -1.321410 -0.853576  1.436926 -1.057146
2  0.092644  1.201601 -0.994798 -2.017163
3 -0.045991 -2.069596  0.011527  0.426753
4 -1.180576 -0.290050  0.678418 -1.086825

D:\python\lib\site-packages\ipykernel_launcher.py:4: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  after removing the cwd from sys.path.

In [ ]:
df = pd.DataFrame(np.random.randn(8, 4), columns = ['A', 'B', 'C', 'D'])
# Index slicing
print(df.ix[:,'A'])

0   -0.470479
1    0.185088
2   -1.624392
3   -0.549156
4    0.494236
5    0.147245
6   -1.273751
7   -0.981244
Name: A, dtype: float64

D:\python\lib\site-packages\ipykernel_launcher.py:3: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  This is separate from the ipykernel package so we can avoid doing imports until

## 11.8 Data alignment and arithmetic

 - Data alignment between DataFrame objects automatically align on both the columns and the index (row labels).
 - Again, the resulting object will have the union of the column and row labels.

In [148]:
df1 = pd.DataFrame(np.random.randn(10, 4), columns=['A', 'B', 'C', 'D'])
df1

          A         B         C         D
0 -0.040813  2.418509 -0.624035 -1.817354
1  0.829584 -0.903151 -1.222098  0.440428
2  1.988854 -0.697703  0.856619  0.402018
3  0.457990  0.156931 -0.675217  0.276451
4  0.190149  0.044447 -0.266396 -0.813976
5  0.199795 -0.158743  0.193317 -1.306953
6  0.792796  0.715538  0.848740  0.726221
7 -1.800187  0.187174 -0.191977 -1.292989
8 -1.340283 -0.462219 -1.927176 -0.813404
9  0.840890 -0.330980 -0.946968 -0.029826

In [ ]:

df2 = pd.DataFrame(np.random.randn(7, 3), columns=['A', 'B', 'C'])
df2

          A         B         C
0 -1.676725 -1.169031 -0.619940
1 -0.710089  1.834536 -1.118924
2 -1.306510 -1.427194  1.891368
3  0.707823  1.638324 -1.007516
4  0.552295 -2.373425 -1.137115
5  0.080897 -0.467685  0.484710
6 -0.478739 -0.519066  0.058221

In [ ]:
df1+df2

          A         B         C   D
0 -1.794426 -0.380882  0.157008 NaN
1 -0.105636  1.346731  0.238002 NaN
2 -2.193027 -1.382245  1.915186 NaN
3  1.275037  2.540692 -0.872054 NaN
4 -0.022608 -1.817870 -1.231789 NaN
5 -0.006301 -1.253170  1.012196 NaN
6 -0.591600  0.601538 -0.875449 NaN
7       NaN       NaN       NaN NaN
8       NaN       NaN       NaN NaN
9       NaN       NaN       NaN NaN

- When doing an operation between DataFrame and Series, the default behavior is to align the Series index on the DataFrame columns, thus broadcasting row-wise. For example:

In [ ]:
df1 - df1.iloc[0]

          A         B         C         D
0  0.000000  0.000000  0.000000  0.000000
1  0.722153 -1.275955  0.579979  1.168068
2 -0.768817 -0.743200 -0.753129  3.333801
3  0.684915  0.114219 -0.641486  1.107699
4 -0.457204 -0.232595 -0.871622  1.034753
5  0.030502 -1.573633 -0.249461  1.452675
6  0.004839  0.332455 -1.710617  0.926712
7  0.454640 -0.679244 -1.072280 -1.831968
8 -1.914198  0.502551  0.236857  1.494064
9  0.096250 -3.020167 -2.132890  1.015062

 - In the special case of working with time series data, and the DataFrame index also contains dates, the broadcasting will be column-wise:

In [149]:
index = pd.date_range('1/1/2000', periods=8)
df = pd.DataFrame(np.random.randn(8, 3), index=index, columns=list('ABC'))
df


# Example

index = pd.date_range('9/1/2026', periods=5)  # Creates 5 consecutive dates

df = pd.DataFrame(
    np.random.randn(5, 3),
    index=index,
    columns=list('XYZ')
)  # Creates a 5-row, 3-column DataFrame with random values

print(df)  # Prints the DataFrame

                   X         Y         Z
2026-09-01  0.028463 -0.624087  1.567919
2026-09-02  0.192350 -0.683648  0.557829
2026-09-03 -1.336354 -1.740822  0.922988
2026-09-04  1.121508 -0.358937  1.290651
2026-09-05 -1.790198 -0.688372 -1.640811

In [ ]:
df1* 10 + 2

           A          B          C          D
0   0.822999   9.881489   9.769477  -9.596196
1   8.044527  -2.878058  15.569265   2.084481
2  -6.865170   2.449487   2.238184  23.741809
3   7.672145  11.023680   3.354615   1.480795
4  -3.749036   7.555543   1.053260   0.751332
5   1.128016  -5.854845   7.274863   4.930555
6   0.871390  13.206037  -7.336697  -0.329076
7   5.369398   3.089045  -0.953321 -27.915874
8 -18.318978  14.906997  12.138047   5.344443
9   1.785502 -20.320177 -11.559426   0.554421

In [144]:
1/df1

NameError: name 'df1' is not defined

In [145]:
df1**5

NameError: name 'df1' is not defined

- Boolean operators work as well:

In [146]:
df1 = pd.DataFrame({'a' : [1, 0, 1], 'b' : [0, 1, 1] }, dtype=bool)
df1

# Example

df1 = pd.DataFrame(
    {
        'Archive': [1, 0, 1],
        'Design': [0, 1, 1]
    },
    dtype=bool
)  # Converts 1 to True and 0 to False

print(df1)  # Prints the Boolean DataFrame

   Archive  Design
0     True   False
1    False    True
2     True    True

In [ ]:
df2 = pd.DataFrame({'a' : [0, 1, 1], 'b' : [1, 1, 0] }, dtype=bool)
df2

       a      b
0  False   True
1   True   True
2   True  False

In [ ]:
df1&df2

       a      b
0  False  False
1  False   True
2   True  False

In [ ]:
df1 | df2

      a     b
0  True  True
1  True  True
2  True  True

In [ ]:
df1^df2

       a      b
0   True   True
1   True  False
2  False   True

In [ ]:
-df1

       a      b
0  False   True
1   True  False
2  False  False

## 11.9 transposing

- To transpose, access the T attribute (also the transpose function), similar to an ndarray:

In [143]:
# only show the first 4 rows
df[:4].T

# Example

# Shows only the first 3 rows, then transposes the DataFrame
df[:3].T

        Archive  Design  Research
Image        10      40         0
Video        20       0         0
Text         30       0         0
Audio         0      50         0
Web           0      60         0
Survey        0       0        70
EEG           0       0        80
AI            0       0        90